import time

def get_model_geninfo(docsymbol: str, data_compiler: str):
    strs = [
        docsymbol + " generated by JxTableCompiler",
        docsymbol + " github: https://github.com/JomiXedYu/JxTableCompiler",
        docsymbol + " model generator: " + data_compiler,
        docsymbol + " generated time: " + time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()) 
    ]
    return "\n".join(strs)